# Site wide configuration

title: Buildit
description: "Builtit open source projects, presentations and developer blog"
logo: 120x120.gif
teaser: 400x250.gif
locale: en
logo: buildit.png

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: David Moss
  email: david.moss@wipro.com
  twitter: mossy
  avatar: bio-photo.jpg
  google:
    plus: damoss07
  disqus-shortname: builditwd


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
